/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cmu.edu.cmu.pocketsphinx;

public class JsgfRule {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected JsgfRule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JsgfRule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SphinxBaseJNI.delete_JsgfRule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  private JsgfRule() {
    this(SphinxBaseJNI.new_JsgfRule(), true);
  }

  public static JsgfRule fromIter(SWIGTYPE_p_jsgf_rule_iter_t itor) {
    long cPtr = SphinxBaseJNI.JsgfRule_fromIter(SWIGTYPE_p_jsgf_rule_iter_t.getCPtr(itor));
    return (cPtr == 0) ? null : new JsgfRule(cPtr, false);
  }

  public String getName() {
    return SphinxBaseJNI.JsgfRule_getName(swigCPtr, this);
  }

  public boolean isPublic() {
    return SphinxBaseJNI.JsgfRule_isPublic(swigCPtr, this);
  }

}
