/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cmu.edu.cmu.pocketsphinx;

public class SegmentIterator implements java.util.Iterator<Segment> {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SegmentIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SegmentIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PocketSphinxJNI.delete_SegmentIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  @Override
  public void remove() {
    throw new UnsupportedOperationException();
  }

  public void setPtr(SWIGTYPE_p_ps_seg_t value) {
    PocketSphinxJNI.SegmentIterator_ptr_set(swigCPtr, this, SWIGTYPE_p_ps_seg_t.getCPtr(value));
  }

  public SWIGTYPE_p_ps_seg_t getPtr() {
    long cPtr = PocketSphinxJNI.SegmentIterator_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ps_seg_t(cPtr, false);
  }

  public SegmentIterator(SWIGTYPE_p_ps_seg_t ptr) {
    this(PocketSphinxJNI.new_SegmentIterator(SWIGTYPE_p_ps_seg_t.getCPtr(ptr)), true);
  }

  public Segment next() {
    long cPtr = PocketSphinxJNI.SegmentIterator_next(swigCPtr, this);
    return (cPtr == 0) ? null : new Segment(cPtr, true);
  }

  public boolean hasNext() {
    return PocketSphinxJNI.SegmentIterator_hasNext(swigCPtr, this);
  }

}
